module.exports = [
	{
		group: 'Lunedì 5 Luglio',
		nome: 'Colazione',
		inizio: '8:00',
		fine: '8:30',
		luogo: 'Caffè degli Specchi',
		id: '01',
	},
	{
		group: 'Lunedì 5 Luglio',
		nome: 'Presentazione ESOF 2019',
		inizio: '8:30',
		fine: '10:30',
		luogo: "Piazza Unità d'Italia",
		id: '02',
	},
	{
		group: 'Lunedì 5 Luglio',
		nome: 'Conclusione',
		inizio: '10:30',
		fine: '11:00',
		luogo: 'Porto Vecchio',
		id: '03',
	},
	{
		group: 'Mercoledì 7 Luglio',
		nome: 'Colazione',
		inizio: '7:30',
		fine: '8:30',
		luogo: 'Caffè degli Specchi',
		id: '04',
	},
	{
		group: 'Mercoledì 7 Luglio',
		nome: 'Il Mondo del Caffè',
		inizio: '8:30',
		fine: '10:00',
		luogo: 'Eataly',
		id: '05',
	},
	{
		group: 'Mercoledì 7 Luglio',
		nome: 'Perchè il Caffè Italiano',
		inizio: '10:00',
		fine: '10:30',
		luogo: 'Eatly',
		id: '06',
	},
	{
		group: 'Mercoledì 7 Luglio',
		nome: "Cos'è la Degustazione 1 - Briefing",
		inizio: '10:30',
		fine: '11:30',
		luogo: 'Eatly',
		id: '07',
	},
	{
		group: 'Mercoledì 7 Luglio',
		nome: 'Riflessioni Finali',
		inizio: '11:30',
		fine: '12:00',
		luogo: "Piazza Unità d'Italia",
		id: '08',
	},
	{
		group: 'Venerdì 9 Luglio',
		nome: 'Colazione',
		inizio: '9:00',
		fine: '9:30',
		luogo: 'Caffè degli Specchi',
		id: '09',
	},
	{
		group: 'Venerdì 9 Luglio',
		nome: 'Illy nel Mondo',
		inizio: '9:30',
		fine: '10:30',
		luogo: 'Piazza della Borsa',
		id: '10',
	},
	{
		group: 'Venerdì 9 Luglio',
		nome: "Cos'è la Degustazione 2 - Hands On",
		inizio: '10:30',
		fine: '11:00',
		luogo: 'Eatly',
		id: '11',
	},
	{
		group: 'Venerdì 9 Luglio',
		nome: 'Fine ESOF 2020',
		inizio: '11:00',
		fine: '12:00',
		luogo: "Piazza Unità d'Italia",
		id: '12',
	},
]
